require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'EmarsysApp' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should uncomment the next line.
  #
  # use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

  # Note that if you have use_frameworks! enabled, RNEmarsysWrapper will not work and
  # you should uncomment the following lines.
  #
  # pod 'RNEmarsysWrapper', :path => '../node_modules/react-native-emarsys-wrapper'
  # pre_install do |installer|
  #   installer.pod_targets.each do |pod|
  #     if pod.name.eql?('RNEmarsysWrapper')
  #       def pod.build_type
  #         Pod::BuildType.static_library
  #       end
  #     end
  #   end
  # end

  use_native_modules!

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target "EmarsysAppNotificationService" do
  pod 'EmarsysNotificationService'
end
